recipe: default.v1
assistant_id: spacy_interesch
language: ru

pipeline:
  - name: SpacyNLP
    model: "ru_core_news_sm"
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
    pooling: mean
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100

policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: TEDPolicy
    epochs: 20
